# Generated by Django 4.2 on 2024-05-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotil', '0006_remove_proyecto_tarea_a_realizar_tarea_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustotil.proyecto'),
        ),
    ]
